version: 5.0.0.{build}
image: Visual Studio 2019
environment:
  PY_DIR: C:/Python39-x64
  MSBUILD_ADDITIONAL_OPTIONS: /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  VSTEST_ADDITIONAL_OPTIONS: /logger:Appveyor
init:
  - set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
install:
  - git submodule init  
  - git submodule update
build_script:
  - cmd: build.bat
test_script:
  - '"bwapi/Debug/BWAPILIBUnitTest.exe" --gtest_output=xml:unit_test_results.xml'
after_test:
  - 'curl -F "file=@unit_test_results.xml" "https://ci.appveyor.com/api/testresults/junit/%APPVEYOR_JOB_ID%"'
artifacts:
  - path: BWAPI.7z
    name: Archive
deploy: off
cache:
  - bwapi\packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3