version: 5.0.0.{build}
image: Visual Studio 2019
environment:
  PY_DIR: C:/Python39-x64
init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
build_script:
  - cmd: build.bat
test_script:
  - '"bwapi/Debug/BWAPILIBUnitTest.exe" --gtest_output=xml:unit_test_results.xml'
  - curl "https://ci.appveyor.com/api/testresults/junit/%APPVEYOR_JOB_ID%" --upload-file unit_test_results.xml
artifacts:
  - path: BWAPI.7z
    name: Archive
deploy: off
cache:
  - bwapi\packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
