version: 5.0.0.{build}
image: Visual Studio 2019
build_script:
- cmd: build.bat
test:
  assemblies:
    only:
    - 'bwapi/Debug/BWAPILIBUnitTest.exe'
artifacts:
- path: BWAPI.7z
  name: Archive
deploy: off
cache:
  - bwapi/packages -> **/packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
